---

- name: Check if DeDRM has already been unpacked
  stat:
    path: "{{ dedrm_unpack_dir }}"
  register: dedrm_unpack_check

- set_fact:
    have_dedrm: "{{ dedrm_unpack_dir.stat.isdir is defined and dedrm_unpack_dir.stat.isdir }}"

- name: DeDRM already fetched
  debug:
    msg: "DeDRM is already unpacked in {{ dedrm_unpack_dir }}"
  when: have_dedrm | bool

- name: Check if we need to fetch DeDRM
  stat:
    path: "{{ dedrm_download_file }}"
  register: dedrm_download_check
  when: not have_dedrm

- set_fact:
    have_dedrm_download: "{{ have_dedrm or (dedrm_download_check.stat.isreg is defined and dedrm_download_check.stat.isreg) }}"

- name: Download DeDRM
  get_url:
    url: "{{ dedrm_url }}"
    dest: "{{ dedrm_download_file }}"
    mode: '0600'
  when: not have_dedrm_download | bool

- name: Create DeDRM directory
  file:
    path: "{{ dedrm_unpack_dir }}"
    mode: '0700'
    state: directory

- name: Unpack DeDRM
  unarchive:
    src: "{{ dedrm_download_file }}"
    dest: "{{ dedrm_unpack_dir }}"
    remote_src: yes
  when: not have_dedrm | bool

- name: Create DeDRM plugin directory
  file:
    path: "{{ dedrm_plugin_unpack_dir }}"
    mode: '0700'
    state: directory

- name: Check if DeDRM plugin is already unpacked
  find:
    paths: "{{ dedrm_plugin_unpack_dir }}"
    patterns: '*'
  register: plugin_unpack_contents

- name: Unpack DeDRM plugin
  unarchive:
    src: "{{ dedrm_plugin }}"
    dest: "{{ dedrm_plugin_unpack_dir }}"
    remote_src: yes
  when: plugin_unpack_contents.matched == 0

- name: Tweak plugin to run wine with PYTHONPATH=""
  replace:
    path: "{{ dedrm_plugin_unpack_dir }}/wineutils.py"
    regexp: '(cmdline\s+=\s+u?"(?!PYTHONPATH))'
    replace: '\1PYTHONPATH=\"\" '
  when: dedrm_pythonpath_fix

- name: Re-pack tweaked plugin
  archive:
    path: "{{ dedrm_plugin_unpack_dir }}/*"
    dest: "{{ dedrm_fixed_plugin }}"
    format: zip
  when: dedrm_pythonpath_fix

- name: Install plugin into Calibre
  command:
    calibre-customize --add-plugin={{ dedrm_fixed_plugin if dedrm_pythonpath_fix else dedrm_plugin }}
  args:
    creates: "{{ installed_plugin }}"
