---

dependencies:
  - role: win_install
    vars:
      pkg_name: Python
      pkg_version: "{{ python_version }}"
      pkg_installed_into_dir: "{{ python_install_dir }}"
      pkg_installer_url: "https://www.python.org/ftp/python/{{ python_version }}/python-{{ python_version }}.exe"
      pkg_installer_ext: "exe"
      pkg_opts:
        Python: "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0"
      pkg_message:
        Python: "Python-{{ python_version }} will install silently."
