---

dedrm_version: "6.8.0"

wine_prefix: "{{ ansible_env.HOME }}/.wine_dedrm"
wine_architecture: "32" # 64 probably doesn't work

# Change this if you are doing lots of runs and want to avoid
# re-downloading every time.
download_dir: "{{ wine_prefix }}"
# download_dir: "{{ ansible_env.HOME }}/.wine_dedrm_installers"

install_kindle: true

# DeDRM reports that 1.7 is no longer supported; as such, this will
# use 4.5.
install_adobe: true

# Probably don't want to change these.
python_version: "2.7.13"
pycrypto_version: "2.6.1"

# These probably shouldn't be customised; they're defined here for
# remove-plugin.yml and internal definitions.
config_dir: "{{ ansible_env.XDG_CONF_DIR | default( ansible_env.HOME + '/.config' ) }}"
calibre_plugin_dir: "{{ config_dir }}/calibre/plugins/"
installed_plugin: "{{ calibre_plugin_dir }}/DeDRM.zip"
plugin_config_file: "{{ calibre_plugin_dir }}/dedrm.json"
