---

- hosts: localhost

  any_errors_fatal: true

  vars_files:
    - configuration.yml

  environment:
    WINEPREFIX: "{{ wine_prefix }}"
    WINEARCH: "win{{ wine_architecture }}"
    # Suppress some warnings
    WINEDEBUG: -msvcrt

  pre_tasks:
    - name: Ensure download directory exists
      file:
        path: "{{ download_dir }}"
        mode: '0700'
        state: directory
      # If it's the wineprefix, then don't create or we can't tell if
      # we need to initialise it.  Just make sure that the wineprefix
      # role is the first one we do.
      when: wine_prefix != download_dir

  # Install

  roles:
    - name: Configuring Wine prefix
      role: wineprefix
      environment:
        # Disables menu entries and mimeconfig; we don't want all the
        # random notepad.exe associations, etc.
        #
        # https://wiki.winehq.org/FAQ#How_can_I_prevent_Wine_from_changing_the_filetype_associations_on_my_system_or_adding_unwanted_menu_entries.2Fdesktop_links.3F
        WINEDLLOVERRIDES: winemenubuilder.exe=d

    - name: Installing Python dependencies
      role: python
      environment:
        # Disables menu entries and mimeconfig; Python is only used
        # internally and doesn't need to be accessed from outside.
        #
        # https://wiki.winehq.org/FAQ#How_can_I_prevent_Wine_from_changing_the_filetype_associations_on_my_system_or_adding_unwanted_menu_entries.2Fdesktop_links.3F
        WINEDLLOVERRIDES: winemenubuilder.exe=d

    - name: Getting DeDRM
      role: dedrm

    - name: Installing Kindle
      role: winetricks
      vars:
        package_name: "kindle"
      when: install_kindle

    - name: Installing Adobe Digital Editions 1.x
      role: winetricks
      vars:
        package_name: "adobe_diged"
      when: install_adobeDE_1

    - name: Installing Adobe Digital Editions 4.y
      role: winetricks
      vars:
        package_name: "adobe_diged4"
      when: install_adobeDE_4
