---

dependencies:
  - role: wineprefix
  - role: dedrm
  - role: python

  # Taken from https://patdavid.net/2018/05/installing-adobe-digital-editions-on-linux-with-wine/
  - role: winetricks
    vars:
      package_name: "corefonts"
  - role: winetricks
    vars:
      package_name: "dotnet35sp1"

  - role: win_install
    vars:
      pkg_name: Adobe
      pkg_version: 2.0
      pkg_installed_into_dir: "{{ adobe_install_dir }}"
      pkg_installer_url: "{{ adobe_url }}"
      pkg_installer_ext: "exe"
      pkg_message:
        Adobe: >-
          Please accept all defaults in the installer window that
          appears (disabling shortcuts is OK).
