---

adobe_url: "http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe"
adobe_installer: "{{ download_dir }}/ADE_2.0_Installer.exe"

adobe_keyfile: "{{ dedrm_unpack_dir }}/adobekey.der"

# Unfortunately this is hardcoded for the version number.
adobe_path: "{{ wine_prefix }}/drive_c/Program Files/Adobe/Adobe Digital Editions 2.0/DigitalEditions.exe"
