---

- name: "Check if {{ pkg_name }} is already installed"
  stat:
    path: "{{ wine_prefix }}/drive_c/{{ pkg_installed_into_dir }}"
  register: pkg_install_check

- set_fact:
    need_app: pkg_install_check.stat.isdir is not defined or not pkg_install_check.stat.isdir

- name: Package is already installed
  debug:
    msg: "{{ pkg_name }} is already installed in {{ wine_prefix }}"
  when: not need_app|bool

- name: Check if we need to download the installer
  stat:
    path: "{{ pkg_installer_path }}"
  register: installer_check
  when: need_app|bool

- set_fact:
    need_installer: need_app and (installer_check.stat.isreg is not defined or not installer_check.stat.isreg)

- name: Download installer
  get_url:
    url: "{{ pkg_installer_url }}"
    dest: "{{ pkg_installer_path }}"
    mode: '0600'
  when: need_installer|bool

- debug:
    msg: Please accept all defaults in the installer window that appears.
  when: need_app|bool

- name: "Installing {{ pkg_name }}"
  command:
    msiexec /i {{ pkg_installer_path }}
  when: need_app|bool
