---

- name: "Check if {{ pkg_name }} is already installed"
  stat:
    path: "{{ wine_prefix }}/drive_c/{{ pkg_installed_into_dir }}"
  register: pkg_install_check

- set_fact:
    have_app: "{{ pkg_install_check.stat.isdir is defined and pkg_install_check.stat.isdir }}"

- name: Package is already installed
  debug:
    msg: "{{ pkg_name }} is already installed in {{ wine_prefix }}"
  when: have_app | bool

- name: Check if we need to download the installer
  stat:
    path: "{{ pkg_installer_path }}"
  register: installer_check
  when: not have_app | bool

- set_fact:
    have_installer: "{{ have_app or (installer_check.stat.isreg is defined and installer_check.stat.isreg) }}"

- name: Download installer
  get_url:
    url: "{{ pkg_installer_url }}"
    dest: "{{ pkg_installer_path }}"
    mode: '0600'
  when: not have_installer | bool

- debug:
    msg: Please accept all defaults in the installer window that appears.
  when: not have_app | bool

- name: "Installing {{ pkg_name }}"
  command:
    msiexec /i {{ pkg_installer_path }}
  when: not have_app | bool
