---

- set_fact:
    package_is_installed: "{{ package_name is in winetricks_installed }}"

- name: Package is already installed
  debug:
    msg: "{{ package_name }} is already installed in {{ wine_prefix }}"
  when: package_is_installed | bool

- name: "Installing {{ package_name }}"
  command:
    winetricks --unattended --force {{ package_name }}
  when: not package_is_installed | bool

- name: Ensure {{ package_name }} finishes installing
  command:
    wineserver --kill
  when: not package_is_installed | bool

- name: Check if Windows version still set to 7
  shell:
    wine regedit /E - 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' | dos2unix
  register: win_version_check
  changed_when: false
  when: not package_is_installed | bool

  # https://github.com/Winetricks/winetricks/issues/1602
- name: Set Windows back to Win7 in case it was changed
  command:
    winetricks --unattended win7
  when: >
    (not package_is_installed | bool) and
    ('"CurrentVersion"="6.1"' not in win_version_check.stdout)
