---

- name: Check if wine prefix already exists
  stat:
    path: "{{ wine_prefix }}"
  register: wine_prefix_check

- set_fact:
    have_prefix: "{{ wine_prefix_check.stat.isdir is defined and wine_prefix_check.stat.isdir }}"

- name: Prefix already exists
  debug:
    msg: "{{ wine_prefix }} already exists"
  when: have_prefix | bool

- name: "Create wine prefix {{ wine_prefix }}"
  command:
    cmd: wine wineboot --init
    creates: "{{ wine_prefix }}"
      # This duplicates the when conditional check
  when: not have_prefix | bool

- name: See if crash dialogs are disabled
  shell:
    wine regedit /E - 'HKEY_CURRENT_USER\Software\Wine\WineDbg' | dos2unix
  register: crash_dialog_check
  changed_when: false

  # See https://wiki.winehq.org/FAQ#How_do_I_disable_the_GUI_crash_dialog.3F
- name: Disable crash dialogs in Wine
  command:
    winetricks nocrashdialog
  when: >
      ('"ShowCrashDialog"=dword:00000000' not in crash_dialog_check.stdout)

- name: "Find out what is installed already with winetricks"
  command:
    winetricks --unattended list-installed
  register: winetricks_installed
  # This should have no side effects
  changed_when: false

- name: Clean up installed list
  set_fact:
    winetricks_installed: "{{ winetricks_installed.stdout }}"
